# Generated by Django 5.0 on 2024-01-03 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="client_name",
        ),
    ]
