# Generated by Django 5.0 on 2024-01-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_remove_event_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_update",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
